version: '3.8'

services:
  # PHP service
  php:
    build:
      context: ./docker/php
    volumes:
      - ./docker/php/docker-entrypoint.sh:/docker-entrypoint.sh
      - ./symfony:/var/www/symfony
    depends_on:
      - mysql
    entrypoint: [ "/bin/sh", "/docker-entrypoint.sh" ]
    command: php-fpm
    networks:
      - app-network

  # Nginx service
  nginx:
    build:
      context: ./docker/nginx
    ports:
      - "80:80"
    volumes:
      - ./symfony:/var/www/symfony
    depends_on:
      - php
    networks:
      - app-network

  # MySQL service
  mysql:
    build:
      context: ./docker/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  # Node.js service for Vue.js frontend
  node:
    build:
      context: ./docker/node
    ports:
      - "8080:8080"
    volumes:
      - ./vue:/app
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    networks:
      - app-network
    command: sh -c "cd /app && npm install && npm run dev"
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data: